library identifier: "pipeline-library@v1.6",
retriever: modernSCM(
  [
    $class: "GitSCMSource",
    remote: "https://github.com/redhat-cop/pipeline-library.git"
  ]
)

openshift.withCluster() {
  env.NAMESPACE = openshift.project()
  env.POM_FILE = env.BUILD_CONTEXT_DIR ? "${env.BUILD_CONTEXT_DIR}/pom.xml" : "pom.xml"
  echo "Starting Pipeline for ${env.APP_NAME}..."
  env.BUILD = "${env.NAMESPACE_BUILD}"
  env.DEV = "${env.NAMESPACE_DEV}"
  env.STAGE = "${env.NAMESPACE_STAGE}"
  env.PROD = "${env.NAMESPACE_PROD}"
}

pipeline {
  // Use Jenkins Maven slave
  // Jenkins will dynamically provision this as OpenShift Pod
  // All the stages and steps of this Pipeline will be executed on this Pod
  // After Pipeline completes the Pod is killed so every run will have clean
  // workspace
  agent {
    label 'maven'
  }

  // Pipeline Stages start here
  // Requeres at least one stage
  stages {

    // Checkout source code
    // This is required as Pipeline code is originally checkedout to
    // Jenkins Master but this will also pull this same code to this slave
    stage('Git Checkout') {
      steps {
        // Turn off Git's SSL cert check, uncomment if needed
        // sh 'git config --global http.sslVerify false'
        git url: "${APPLICATION_SOURCE_REPO}", branch: "${APPLICATION_SOURCE_REF}"
      }
    }

    // Run Maven build, skipping tests
    stage('Build'){
      steps {
        sh "mvn -B clean install -DskipTests=true -f ${POM_FILE}"
      }
    }

    // Run Maven unit tests
    stage('Unit Test'){
      steps {
        sh "mvn -B test -f ${POM_FILE}"
      }
    }

    // Build Container Image using the artifacts produced in previous stages
    stage('Build Container Image'){
      steps {
       input message: 'Build container Image'
      }
    }

    stage('Promote from Build to Dev') {
      steps {
        input message: 'Promote from Build to Dev'
      }
    }

    stage ('Verify Deployment to Dev') {
      steps {
        input message: 'verify from deployment to Dev'
      }
    }

    stage('Promote from Dev to Stage') {
      steps {
       input message: 'Promote from dev to stage'
      }
    }

    stage ('Verify Deployment to Stage') {
      steps {
        input message: 'Verify Deployment to Stage'
      }
    }

    stage('Promotion gate') {
      steps {
        script {
          input message: 'Promote igate?'
        }
      }
    }

    stage('Promote from Stage to Prod') {
      steps {
        input message: 'Promote from Stage to Prod'
      }
    }

    stage ('Verify Deployment to Prod') {
      steps {
        input message: 'Verify Deployment to Prodv'
      }
    }
  }
}
